#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。
name: eecuper
# 描述/签名
description: 点滴记录,33不惑

#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: http://py4c6bw1i.bkt.clouddn.com/gyhx.jpg?e=1569379697&token=8kwWa7JjWPpVYud7UyzLK43qkfYoAK2pr9w3axO_:Hn7XA9RXy2-JgfqghAbGcK29BOg

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: http://py4c6bw1i.bkt.clouddn.com/eevee_red.png?e=1569383005&token=8kwWa7JjWPpVYud7UyzLK43qkfYoAK2pr9w3axO_:RgXfl2ic_1AB-L4RrAzZmb0ZpCM


# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags
  simple_jekyll_search:
    enable: true
    autoloader: /public/simple-jekyll-search/autoloader.js
    stylesheet: /public/simple-jekyll-search/search_box.css
    src: //cdn.jsdelivr.net/npm/simple-jekyll-search/dest/simple-jekyll-search.min.js
    placeholder: 搜索博文
    json: /public/simple-jekyll-search/search.json
  jekyll_table_of_contents:
    enable: true
    autoloader: /public/js/jekyll_table_of_contents.js
    src: //cdn.jsdelivr.net/gh/ghiculescu/jekyll-table-of-contents/toc.js
  busuanzi:
    enable: true
    src: //cdn.jsdelivr.net/npm/busuanzi/bsz.pure.mini.js
    page_pv: # 页面访问量
      alert: <i class="fas fa-eye fa-fw"></i>
      unit: 次
    site_pv: # 站点访问量
      alert: <i class="fas fa-paw fa-fw"></i>
      unit: 枚
    site_uv: # 访客量
      alert: <i class="fas fa-user-friends fa-fw"></i>
      unit: 人
  last_edit:
    enable: true
    alert: <i class="fas fa-user-edit fa-fw"></i>
  run_time:
    enable: true
    src: /public/js/run_time.js
    start_time: '10/04/2017 11:03:56' # 这是我第一篇CSDN博客的时间
    alert: <i class="fas fa-cog fa-spin fa-fw"></i>
    day: 天
    hour: 时
    minute: 分
    second: 秒
  copyright:
    enable: true
    text: '<script async defer src="https://buttons.github.io/buttons.js"></script><a class="github-button" aria-label="Star wu-kan/wu-kan.github.io on GitHub" href="https://github.com/wu-kan/wu-kan.github.io" data-icon="octicon-star" data-show-count="true">Star</a>'    

# 每页的文章数
paginate: 8

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo:  #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: 404810628@qq.com 
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: http://leeqoo.github.io #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: rss #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: Copyright (c) 2019 eecuper
 

# 输入Disqus shortname，即可添加评论区，细节可阅读文档。
disqus: Disqus shortname #loffer 

# 输入Google Analytics web tracking code
google_analytics:

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: 

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

excerpt_separator: ---
