# Site settings
title: eecuper
email: 404810628@qq.com
description: > # this means to ignore newlines until "baseurl:"
  eecuper
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://www.eecuper.com # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: lee c 

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
# twitter: suyan404
# weibo: suyan0830
# github: suyan
# instagram: suyan404
# linkedin: suyan404

# avatar and Favicon
avatar: http://py4c6bw1i.bkt.clouddn.com/gyhx.jpg?e=1571278933&token=8kwWa7JjWPpVYud7UyzLK43qkfYoAK2pr9w3axO_:hYLcwwz7Z8_k8z361NRYaH4jnWc
favicon: http://py4c6bw1i.bkt.clouddn.com/uper-logo.jpg?e=1571279364&token=8kwWa7JjWPpVYud7UyzLK43qkfYoAK2pr9w3axO_:-gd8ctBfn77V6kJppBUURk_aAlA

# disqus config
disqus:
  shortname: lichao-zh

# google analytics config
# ga:
#   id: UA-54767140-1
#   url: yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

